networks:
  monitor-net:
      driver: bridge

services:
  # --- Application Stack ---
  postgres:
    image: postgres:16
    hostname: postgres
    environment:
      - POSTGRES_USER=demouser
      - POSTGRES_PASSWORD=demopassword
      - POSTGRES_DB=demodb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - monitor-net

  query-simulator:
    build:
      context: ./QuerySimulator
    environment:
      - DB_CONNECTION_STRING=Host=postgres;Port=5432;Username=demouser;Password=demopassword;Database=demodb
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - monitor-net

  # --- Prometheus & Grafana Stack ---
  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    hostname: postgres_exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://demouser:demopassword@postgres:5432/demodb?sslmode=disable
    ports:
      - "9187:9187"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus:v2.53.0
    hostname: prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana-oss:11.1.0
    hostname: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - monitor-net

  # --- Zabbix Stack ---
  zabbix-db:
    image: postgres:16
    hostname: zabbix-db
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbixpass
      - POSTGRES_DB=zabbixdb
    volumes:
      - zabbix_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - monitor-net

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    hostname: zabbix-server
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbixpass
      - POSTGRES_DB=zabbixdb
      - DB_SERVER_HOST=zabbix-db
    depends_on:
      - zabbix-db
    restart: unless-stopped
    networks:
      - monitor-net

  zabbix-agent:
    image: zabbix/zabbix-agent2:latest
    hostname: zabbix-agent
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_HOSTNAME=PostgreSQL Demo DB
    depends_on:
      - zabbix-server
      - postgres
    restart: unless-stopped
    networks:
      - monitor-net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    hostname: zabbix-web
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbixpass
      - POSTGRES_DB=zabbixdb
      - DB_SERVER_HOST=zabbix-db
      - ZBX_SERVER_HOST=zabbix-server
    ports:
      - "8080:8080"
    depends_on:
      - zabbix-server
    restart: unless-stopped
    networks:
      - monitor-net

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
  zabbix_postgres_data:
